app:
  domain: http://localhost:3000

api:
  base: http://localhost:3000/v1

mandrill:
  username: ENV['MANDRILL_USERNAME']
  password: ENV['MANDRILL_PASSWORD']
  from_email: ENV['MANDRILL_FROM_EMAIL']
